version: '3'

services:
  api: 
    build: ./api
    volumes:
      - ./api:/code/
    ports:
      - 5001:8080
    # deploy: 
    #   replicas: 2
  website:
    image: image
    ports:
      - "5000:8080"
    volumes:
      - ./website/ngnix.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  